version: '3.7'

services:
  nginx:
    container_name: auth_nginx
    image: nginx:latest
    volumes:
      - ${APP_HOST_PATH}:${APP_CONTAINER_PATH}
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - 8090:80
    networks:
      - default

  php:
    container_name: auth_php
    build: ${PHP_DOCKERFILE_PATH}
    volumes:
      - ${SSH_HOST_PATH}:/root/.ssh/:ro
      - ${APP_HOST_PATH}:${APP_CONTAINER_PATH}
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1 remote_autostart=1"
    working_dir: ${APP_CONTAINER_PATH}
    expose:
      - 9000
    networks:
      - default

  composer:
    container_name: auth_composer
    image: composer:latest
    volumes:
      - ${APP_HOST_PATH}:${APP_CONTAINER_PATH}
      - ${SSH_HOST_PATH}:/root/.ssh/:ro
    working_dir: ${APP_CONTAINER_PATH}
    command: composer install
